### PR TITLE
undefined Error

### PR DESCRIPTION
**Pull request by daviddusty**
When no vehicles in server and use this method, undefined error will occur.
cannot read property ”arrayOfPositions[0].pos" of undefined

### CODE REVIEW

**Comment by mamadlooloo** [comment]
Why funny???

**Comment by mamadlooloo** [comment]
All about vehicles man. i realized why it was so funny for you.
getClosestVectorFromGroup()
This function has nothing to do with the vehicles while i was writing:
"There are no vehicles in the city"

**Comment by Stuyk** [comment]
Originally when I opened it. It showed that you changed cars to vehicles. Made me laugh.

**Comment by mamadlooloo** [comment]
I'm beginner and i do not understand what you mean by this comment.
Please explain more about Array.isArray

**Comment by Stuyk** [comment]
Sure. This page should suffice.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

**Comment by mamadlooloo** [comment]
I'm using this code
```js
export function getClosestVehicle(player) {
    return getClosestVectorFromGroup(player.pos, [...alt.Vehicle.all]);
}
```
I think second parameter of getClosestVectorFromGroup() is object not array and if i using Array.isArray return false.
Am I right?

**Comment by Stuyk** [comment]
Second parameter is an array using the spread operator.

**Comment by mamadlooloo** [comment]
Edit button in "Files changed" is not active for me.
```js
if (!Array.isArray(arrayOfPositions[0])) {
    throw new Error('There is no vector exist.');
}
```

**Comment by Stuyk** [comment]
I'll reach out to you when I get some time. What is your Discord.

**Comment by mamadlooloo** [comment]
Thank you
JoeMoly#0629

**Comment by mamadlooloo** [comment]
Edit button in "Files changed" is not active for me.
I think good time for closing this pull.
Thank you

**Pull request closed without merging**
